### ISSUE TITLE
KeyError key record not found

### ISSUE THREAD

**Issue by awalias** [supabase/realtime#50]
Possibly introduced in https://github.com/supabase/realtime/tree/951ef2350465d42eb6f741f4659ed5b6fda4cd7b

Realtime version 7.0.5 @ 951ef2350465d42eb6f741f4659ed5b6fda4cd7b

```erlang
2020-06-04 08:21:11.454 [info] "realtime:public"
2020-06-04 08:21:11.454 [info] "realtime:public:product"
2020-06-04 08:21:11.458 [error] GenServer Realtime.SubscribersNotification terminating
** (KeyError) key :record not found in: %Realtime.Adapters.Changes.DeletedRecord{columns: [%Realtime.Decoder.Messages.Relation.Column{flags: [:key], name: "id", type: "uuid", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "name", type: "text", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "ean", type: "text", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "manufacturer", type: "uuid", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "asin", type: "text", type_modifier: 4294967295}], commit_timestamp: ~U[2020-05-31 00:00:48Z], old_record: %{"asin" => nil, "ean" => nil, "id" => "0dfbf2c9-6e9f-494b-bbef-fb35295aad9c", "manufacturer" => nil, "name" => nil}, schema: "public", table: "product", type: "DELETE"}
    (realtime 0.7.1) lib/realtime/subscribers_notification.ex:62: anonymous fn/3 in Realtime.SubscribersNotification.notify_subscribers/1
    (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (realtime 0.7.1) lib/realtime/subscribers_notification.ex:43: Realtime.SubscribersNotification.notify_subscribers/1
    (realtime 0.7.1) lib/realtime/subscribers_notification.ex:24: Realtime.SubscribersNotification.handle_call/3
    (stdlib 3.13) gen_server.erl:706: :gen_server.try_handle_call/4
    (stdlib 3.13) gen_server.erl:735: :gen_server.handle_msg/6
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.2402.0>): {:notify, %Realtime.Adapters.Changes.Transaction{changes: [%Realtime.Adapters.Changes.DeletedRecord{columns: [%Realtime.Decoder.Messages.Relation.Column{flags: [:key], name: "id", type: "uuid", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "name", type: "text", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "ean", type: "text", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "manufacturer", type: "uuid", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "asin", type: "text", type_modifier: 4294967295}], commit_timestamp: nil, old_record: %{"asin" => nil, "ean" => nil, "id" => "0dfbf2c9-6e9f-494b-bbef-fb35295aad9c", "manufacturer" => nil, "name" => nil}, schema: "public", table: "product", type: "DELETE"}], commit_timestamp: ~U[2020-05-31 00:00:48Z]}}
2020-06-04 08:21:11.465 [error] GenServer #PID<0.2402.0> terminating
** (stop) exited in: GenServer.call(Realtime.SubscribersNotification, {:notify, %Realtime.Adapters.Changes.Transaction{changes: [%Realtime.Adapters.Changes.DeletedRecord{columns: [%Realtime.Decoder.Messages.Relation.Column{flags: [:key], name: "id", type: "uuid", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "name", type: "text", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "ean", type: "text", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "manufacturer", type: "uuid", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "asin", type: "text", type_modifier: 4294967295}], commit_timestamp: nil, old_record: %{"asin" => nil, "ean" => nil, "id" => "0dfbf2c9-6e9f-494b-bbef-fb35295aad9c", "manufacturer" => nil, "name" => nil}, schema: "public", table: "product", type: "DELETE"}], commit_timestamp: ~U[2020-05-31 00:00:48Z]}}, 5000)
    ** (EXIT) an exception was raised:
        ** (KeyError) key :record not found in: %Realtime.Adapters.Changes.DeletedRecord{columns: [%Realtime.Decoder.Messages.Relation.Column{flags: [:key], name: "id", type: "uuid", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "name", type: "text", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "ean", type: "text", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "manufacturer", type: "uuid", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "asin", type: "text", type_modifier: 4294967295}], commit_timestamp: ~U[2020-05-31 00:00:48Z], old_record: %{"asin" => nil, "ean" => nil, "id" => "0dfbf2c9-6e9f-494b-bbef-fb35295aad9c", "manufacturer" => nil, "name" => nil}, schema: "public", table: "product", type: "DELETE"}
            (realtime 0.7.1) lib/realtime/subscribers_notification.ex:62: anonymous fn/3 in Realtime.SubscribersNotification.notify_subscribers/1
            (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
            (realtime 0.7.1) lib/realtime/subscribers_notification.ex:43: Realtime.SubscribersNotification.notify_subscribers/1
            (realtime 0.7.1) lib/realtime/subscribers_notification.ex:24: Realtime.SubscribersNotification.handle_call/3
            (stdlib 3.13) gen_server.erl:706: :gen_server.try_handle_call/4
            (stdlib 3.13) gen_server.erl:735: :gen_server.handle_msg/6
            (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    (elixir 1.10.3) lib/gen_server.ex:1023: GenServer.call/3
    (realtime 0.7.1) lib/realtime/replication.ex:84: Realtime.Replication.process_message/2
    (realtime 0.7.1) lib/realtime/replication.ex:56: Realtime.Replication.handle_info/2
    (stdlib 3.13) gen_server.erl:680: :gen_server.try_dispatch/4
    (stdlib 3.13) gen_server.erl:756: :gen_server.handle_msg/6
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:epgsql, #PID<0.2403.0>, {:x_log_data, 24207728, 24207728, <<67, 0, 0, 0, 0, 0, 1, 113, 97, 64, 0, 0, 0, 0, 1, 113, 97, 112, 0, 2, 73, 229, 35, 177, 168, 88>>}}
2020-06-04 08:21:11.509 [info] Application realtime exited: shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,realtime,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,realtime,shutdown})

Crash dump is being written to: erl_crash.dump...x_log_data, 24207728, 24207728, <<67, 0, 0, 0, 0, 0, 1, 113, 97, 64, 0, 0, 0, 0, 1, 113, 97, 112, 0, 2, 73, 229, 35, 177, 168, 88>>}}
2020-05-31 00:00:48.677 [info] Application realtime exited: shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,realtime,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,realtime,shutdown})
```

**Comment by fracek** [comment]
The problem seems to be in the channel notifier

https://github.com/supabase/realtime/blob/f830e3ea4ba83e27fa1781c6e901e906634ef4f1/server/lib/realtime/subscribers_notification.ex#L63-L69

You can see the definition of `NewRecord`, `UpdateRecord` and `DeleteRecord` are slightly different in that `NewRecord` has a `record` field, same for `UpdateRecord`. When we delete a record there is no new record but only an `old_record`.

https://github.com/supabase/realtime/blob/f830e3ea4ba83e27fa1781c6e901e906634ef4f1/server/lib/adapters/changes.ex#L5-L12

I can fix this quickly to send all types of changes to the channel.

How did you trigger the deletion?

**Comment by kiwicopple** [comment]
> same for UpdateRecord

Note that UpdateRecord will only receive the old value in some cases:

> [OPTIONAL] If you want to recieve the old record (previous values) on UDPATE and DELETE, you can set the REPLICA IDENTITY to FULL like this: ALTER TABLE your_table REPLICA IDENTITY FULL;. This has to be set for each table unfortunately.

`Logger.info inspect(eq)`

We should change this to a `debug` rather than `info`

> How did you trigger the deletion?

@awalias did you have a repo you're testing on? Othewise I can mock it up into the Next.js example for testing

**Comment by awalias** [comment]
sorry, this was on a user's box so I don't have the delete details

**Comment by awalias** [comment]
hotfixed with 2ece7b1a5061e5988ea5f9d03f2f70f869ebca5d I'm guessing it will need further work to cover the cases you mentioned above?

**Comment by kiwicopple** [comment]
That's perfect @awalias - should work for `UPDATE` too

**Comment by awalias** [comment]
getting a different error now:

```erlang
2020-06-05 17:18:44.270 [info] Running RealtimeWeb.Endpoint with cowboy 2.6.3 at :::4000 (http)
2020-06-05 17:18:44.270 [info] Access RealtimeWeb.Endpoint at http://localhost:4000
2020-06-05 17:18:44.330 [info] "realtime:public"
2020-06-05 17:18:44.330 [info] "realtime:public:dashboard"
2020-06-05 17:18:44.330 [info] "realtime:public:dashboard:id=eq.17ce1beb-f4ed-4d6c-a1e0-1bcc833d9dd0"
2020-06-05 17:18:44.331 [info] "realtime:public:dashboard:name=eq.Saver.nu"
2020-06-05 17:18:44.332 [error] GenServer Realtime.SubscribersNotification terminating
** (ArgumentError) argument error
    :erlang.bit_size(:unchanged_toast)
    (realtime) anonymous fn/3 in Realtime.SubscribersNotification.notify_subscribers/1
    (elixir) lib/enum.ex:789: anonymous fn/3 in Enum.each/2
    (stdlib) maps.erl:232: :maps.fold_1/3
    (elixir) lib/enum.ex:1964: Enum.each/2
    (realtime) lib/realtime/subscribers_notification.ex:64: anonymous fn/3 in Realtime.SubscribersNotification.notify_subscribers/1
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (realtime) lib/realtime/subscribers_notification.ex:44: Realtime.SubscribersNotification.notify_subscribers/1
Last message (from #PID<0.2578.0>): {:notify, %Realtime.Adapters.Changes.Transaction{changes: [%Realtime.Adapters.Changes.UpdatedRecord{columns: [%Realtime.Decoder.Messages.Relation.Column{flags: [:key], name: "id", type: "uuid", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "name", type: "text", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "products", type: "jsonb", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "sources", type: "jsonb", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "showEUR", type: "bool", type_modifier: 4294967295}], commit_timestamp: nil, old_record: %{}, record: %{"id" => "17ce1beb-f4ed-4d6c-a1e0-1bcc833d9dd0", "name" => "Saver.nu", "products" => :unchanged_toast, "showEUR" => "t", "sources" => "[{\"id\": \"c5e37367-39d7-4182-9459-5b4071939cd1\", \"name\": \"prisjakt.se\"}, {\"id\": \"96a7a708-b6ce-4ffe-8db0-6f72ebee2eaf\", \"name\": \"idealo.de\"}, {\"id\": \"50ac5475-e6d1-43b8-b5d3-53807e751a96\", \"name\": \"hintaopas.fi\"}, {\"id\": \"d70c0808-6097-42d1-bafc-b1971679fea3\", \"name\": \"heureka.cz\"}]"}, schema: "public", table: "dashboard", type: "UPDATE"}], commit_timestamp: ~U[2020-06-01 22:54:14Z]}}
2020-06-05 17:18:44.334 [error] GenServer #PID<0.2578.0> terminating
** (stop) exited in: GenServer.call(Realtime.SubscribersNotification, {:notify, %Realtime.Adapters.Changes.Transaction{changes: [%Realtime.Adapters.Changes.UpdatedRecord{columns: [%Realtime.Decoder.Messages.Relation.Column{flags: [:key], name: "id", type: "uuid", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "name", type: "text", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "products", type: "jsonb", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "sources", type: "jsonb", type_modifier: 4294967295}, %Realtime.Decoder.Messages.Relation.Column{flags: [], name: "showEUR", type: "bool", type_modifier: 4294967295}], commit_timestamp: nil, old_record: %{}, record: %{"id" => "17ce1beb-f4ed-4d6c-a1e0-1bcc833d9dd0", "name" => "Saver.nu", "products" => :unchanged_toast, "showEUR" => "t", "sources" => "[{\"id\": \"c5e37367-39d7-4182-9459-5b4071939cd1\", \"name\": \"prisjakt.se\"}, {\"id\": \"96a7a708-b6ce-4ffe-8db0-6f72ebee2eaf\", \"name\": \"idealo.de\"}, {\"id\": \"50ac5475-e6d1-43b8-b5d3-53807e751a96\", \"name\": \"hintaopas.fi\"}, {\"id\": \"d70c0808-6097-42d1-bafc-b1971679fea3\", \"name\": \"heureka.cz\"}]"}, schema: "public", table: "dashboard", type: "UPDATE"}], commit_timestamp: ~U[2020-06-01 22:54:14Z]}}, 5000)
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            :erlang.bit_size(:unchanged_toast)
            (realtime) anonymous fn/3 in Realtime.SubscribersNotification.notify_subscribers/1
            (elixir) lib/enum.ex:789: anonymous fn/3 in Enum.each/2
            (stdlib) maps.erl:232: :maps.fold_1/3
            (elixir) lib/enum.ex:1964: Enum.each/2
            (realtime) lib/realtime/subscribers_notification.ex:64: anonymous fn/3 in Realtime.SubscribersNotification.notify_subscribers/1
            (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
            (realtime) lib/realtime/subscribers_notification.ex:44: Realtime.SubscribersNotification.notify_subscribers/1
    (elixir) lib/gen_server.ex:1009: GenServer.call/3
    (realtime) lib/realtime/replication.ex:84: Realtime.Replication.process_message/2
    (realtime) lib/realtime/replication.ex:56: Realtime.Replication.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:epgsql, #PID<0.2579.0>, {:x_log_data, 110555416, 110555416, <<67, 0, 0, 0, 0, 0, 6, 150, 240, 232, 0, 0, 0, 0, 6, 150, 241, 24, 0, 2, 74, 12, 113, 75, 65, 82>>}}
```

**Comment by fracek** [comment]
I can't reproduce this. I tried to delete and update rows manually using `psql` and the process does not crash.

**Comment by kiwicopple** [comment]
```Last message: {:epgsql, #PID<0.2579.0>, {:x_log_data, 110555416, 110555416, <<67, 0, 0, 0, 0, 0, 6, 150, 240, 232, 0, 0, 0, 0, 6, 150, 241, 24, 0, 2, 74, 12, 113, 75, 65, 82>>}}```

We might be able to run this through one of the tests scripts to replicate. I'm a bit tied up but can get to this later tonight or early tmr

**Comment by kiwicopple** [comment]
@awalias can you let us know where you are finding these errors? On the customer boxes? Are they definitely on the latest commit?

**Comment by kiwicopple** [comment]
OK found the cause of the error: 

```
%{
    "id" => "17ce1beb-f4ed-4d6c-a1e0", 
    "name" => "Saver.nu",
    "products" => :unchanged_toast, 
    "showEUR" => "t", 
    "sources" => "[{\"id\": \"c5e37367-39d7-4182-9459\", \"name\": \"redacted\"}}]"
}
```

Fails on this: 

```
if v != nil do
    eq = table_topic <> ":" <> k <> "=eq." <> v
    RealtimeWeb.RealtimeChannel.handle_realtime_transaction(eq, change)
end
```

The cause must be `sources` which is a stringified array `"[{\"id\": \"c5e37367-39d7-4182-9459\", \"name\": \"redacted\"}}]"`, and then it cant send out the notify to the RealtimeChannel 

@fracek suggested improvements would solve this (we wouldn't do an equality check on an array) - `table_topic <> ":" <> k <> "=eq." <> v`

For now we will have to patch/avoid these sort of strings. Checking the best ways now. @fracek any suggestion?

**Comment by kiwicopple** [comment]
actually `"products" => :unchanged_toast,` is the culprit. Fixing

**Comment by kiwicopple** [comment]
@awalias this is fixed. I don't know the release process that you're using for KPS. Should I bump it ? https://github.com/supabase/realtime#releases

**Comment by kiwicopple** [comment]
Reopening until this is patched & deployed

**Comment by awalias** [comment]
thanks guys for getting to the bottom of this

I will bump and release tonight

**Comment by awalias** [comment]
shipping

**Comment by kwakwaversal** [comment]
Just as a gentle reminder, the `latest` docker image for `supabase/realtime` still has this bug. I tracked it down to this issue and rebuilt from the latest code in the repo using the provided `Dockerfile` and it has resolved.

**Comment by kiwicopple** [comment]
Interesting. thanks for the follow up @kwakwaversal - not sure why it isn't yet shipped to docker

**Comment by relferreira** [comment]
Hello, I'm seen this error in the SaaS Supabase:

<img width="987" alt="Screen Shot 2021-06-21 at 5 27 58 PM" src="https://user-images.githubusercontent.com/4078815/122823815-33362780-d2b6-11eb-827c-d281dedbd3fd.png">

**Comment by w3b6x9** [comment]
@relferreira thanks for reporting your error. Were you listening to [row level changes](https://supabase.io/docs/reference/javascript/subscribe#listening-to-row-level-changes) (e.g. `teams:id=eq.taua`) when this error occurred?

**Comment by relferreira** [comment]
Hello @w3b6x9, yes:
```js
const mySubscription = supabase
          .from(`teams:id=eq.${team}`)
          .on('UPDATE', payload => {
            console.log('Change received!', payload);
            // setTeamInfo(payload.new);
          })
          .subscribe();
```

**Comment by w3b6x9** [comment]
@relferreira thanks for confirming! we'll look into this

**Comment by relferreira** [comment]
@w3b6x9 I don't know if it helps, but this table has 2 json collums

**Comment by w3b6x9** [comment]
@relferreira alright so you can circumvent this issue by either setting your `teams` table's replica identity to `FULL` (`ALTER TABLE teams REPLICA IDENTITY FULL;`) or simply ignore it since there are no changes.

**Comment by relferreira** [comment]
Hello @w3b6x9,
It's been a long time, but thank you for the response.

I think that in the latest release, the `unchanged_toast` is not returning anymore. It is a bug, or was something planned?

Thanks in advance.

**Comment by w3b6x9** [comment]
@relferreira Realtime RLS no longer returns `unchanged_toast`. You'll have to set `REPLICA IDENTITY` to `FULL` If you would like the unchanged column(s) outputted. Please see https://github.com/supabase/realtime/issues/223 for more context.
