### ISSUE TITLE
500 error report

### ISSUE THREAD

**Issue by awalias** [supabase/realtime#72]
service ref `vkvjnvalmrvcmmlggpfr`

```erlang
2020-10-06 06:44:12.538 [error] GenServer #PID<0.2624.0> terminating
** (CaseClauseError) no case clause matching: 3
    (realtime 0.7.7) lib/decoder/decoder.ex:189: Realtime.Decoder.decode_message_impl/1
    (realtime 0.7.7) lib/realtime/replication.ex:52: Realtime.Replication.handle_info/2
    (stdlib 3.13) gen_server.erl:680: :gen_server.try_dispatch/4
    (stdlib 3.13) gen_server.erl:756: :gen_server.handle_msg/6
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:epgsql, #PID<0.2625.0>, {:x_log_data, 207641560, 207641560, <<84, 0, 0, 0, 1, 3, 0, 0, 64, 138>>}}
```

```erlang
2020-10-06 06:44:12.938 [info] Application realtime exited: shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,realtime,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,realtime,shutdown})

Crash dump is being written to: erl_crash.dump...controller,"{application_terminated,realtime,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,realtime,shutdown})

Crash dump is being written to: erl_crash.dump...ion_terminated,realtime,shutdown})

Crash dump is being written to: erl_crash.dump......dump....{application_terminated,realtime,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,realtime,shutdown})

Crash dump is being written to: erl_crash.dump...lication_terminated,realtime,shutdown})

Crash dump is being written to: erl_crash.dump....mp..."{application_terminated,realtime,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,realtime,shutdown})

Crash dump is being written to: erl_crash.dump...ation_controller) ({application_terminated,realtime,shutdown})

Crash dump is being written to: erl_crash.dump...04.935 [info] JOINED realtime:public:project in 144µs
  Parameters: %{}
2020-10-05 04:50:05.034 [info] Application realtime exited: shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,realtime,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,realtime,shutdown})

Crash dump is being written to: erl_crash.dump...ange, :epgsql_idatetime}, 1186 => {:type, 1186, :interval, false, :undefined, :epgsql_codec_datetime, :epgsql_idatetime}, 1115 => {:type, 1115, :timestamp, true, 1114, :epgsql_codec_datetime, :epgsql_idatetime}, 2951 => {:type, 2951, :uuid, true, 2950, :epgsql_codec_uuid, []}, 1014 => {:type, 1014, :bpchar, true, 1042, :epgsql_codec_bpchar, []}, 1183 => {:type, 1183, :time, true, 1083, :epgsql_codec_datetime, :epgsql_idatetime}, 651 => {:type, 651, :cidr, true, 650, :epgsql_codec_net, []}, 3926 => {:type, 3926, :int8range, false, :undefined, :epgsql_codec_intrange, []}, 1000 => {:type, 1000, :bool, true, 16, :epgsql_codec_boolean, ...}, 1187 => {:type, 1187, :interval, true, 1186, ...}, 1043 => {:type, 1043, :varchar, false, ...}, 774 => {:type, 774, :macaddr8, ...}, 3904 => {:type, 3904, ...}, 1040 => {:type, ...}, 3802 => {...}, ...}, %{{:bpchar, true} => 1014, {:timestamptz, true} => 1185, {:timetz, false} => 1266, {:timestamptz, false} => 1184, {:text, true} => 1009, {:date, true} => 1182, {:float4, false} => 700, {:int4range, true} => 3905, {:uuid, false} => 2950, {:char, false} => 18, {:tsrange, false} => 3908, {:cidr, false} => 650, {:varchar, false} => 1043, {:inet, true} => 1041, {:json, true} => 199, {:int8, true} => 1016, {:tstzrange, false} => 3910, {:daterange, true} => 3913, {:int8, false} => 20, {:timestamp, false} => 1114, {:int4, true} => 1007, {:float4, true} => 1021, {:tsrange, true} => 3909, {:time, false} => 1083, {:text, false} => 25, {:timestamp, true} => 1115, {:int2, true} => 1005, {:date, false} => 1082, {:macaddr8, false} => 774, {:macaddr, false} => 829, {:char, true} => 1002, {:bytea, false} => 17, {:cidr, true} => 651, {:daterange, false} => 3912, {:float8, true} => 1022, {:tstzrange, ...} => 3911, {...} => 1270, ...}}}, {[], []}, :undefined, :undefined, :undefined, :undefined, [{"application_name", ""}, {"client_encoding", "UTF8"}, {"DateStyle", "ISO, MDY"}, {"integer_datetimes", "on"}, {"IntervalStyle", "postgres"}, {"is_superuser", "on"}, {"server_encoding", "UTF8"}, {"server_version", "12.3 (Ubuntu 12.3-1.pgdg18.04+1)"}, {"session_authorization", "supabase_admin"}, {"standard_conforming_strings", "on"}, {"TimeZone", "UTC"}], [], [], true, 73, :undefined, {:repl, :undefined, 0, 0, :undefined, :undefined, :undefined, #PID<0.2628.0>, false}}, :undefined)
    (epgsql 4.3.0) /opt/supabase/server/deps/epgsql/src/epgsql_sock.erl:294: :epgsql_sock.command_handle_message/3
    (epgsql 4.3.0) /opt/supabase/server/deps/epgsql/src/epgsql_sock.erl:378: :epgsql_sock.loop/1
    (stdlib 3.13) gen_server.erl:680: :gen_server.try_dispatch/4
    (stdlib 3.13) gen_server.erl:756: :gen_server.handle_msg/6
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:tcp, #Port<0.17>, <<69, 0, 0, 0, 116, 83, 69, 82, 82, 79, 82, 0, 86, 69, 82, 82, 79, 82, 0, 67, 53, 53, 48, 48, 54, 0, 77, 114, 101, 112, 108, 105, 99, 97, 116, 105, 111, 110, 32, 115, 108, 111, 116, 32, 34, 114, 101, ...>>}
```

**Comment by awalias** [comment]
affected line https://github.com/supabase/realtime/blob/c8966564de9a4def5c6a5afc91e5ea53986fe325/server/lib/decoder/decoder.ex#L66

**Comment by kiwicopple** [comment]
Hey @awalias - is this one still occuring for this database? I tried to decode this binary string but found nothing. I couldn't replicate, but if it is still happening I should be able to debug it live

**Comment by kiwicopple** [comment]
Closing - cannot replicate
