### ISSUE TITLE
Supabase Realtime Docker Image Breaking local development

### ISSUE THREAD

**Issue by furquanh** [supabase/realtime#853]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After running npx supabase start I was prompted to install newer versions of the images which I agreed too, but these newer images broke the local development setup because the container doesn't start anymore. The issue particularly lies in the supabase/realtime image health check api that is running a query on some table called tenants where the jwt_jwks column doesn't exist.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new next app: npx create-next-app -e with-supabase
2. Have a edge function defined: npx supabase function new myFunction
3. Start the container: npx supabase start

## Screenshots

```
             Request: HEAD /api/tenants/realtime-dev/health
                                                           ** (exit) an exception was raised:
                                                                                                 ** (CaseClauseError) no case clause matching: {:error, "ERROR 42703 (undefined_column) column t0.jwt_jwks does not exist\n\n    query: SELECT t0.\"id\", t0.\"name\", t0.\"external_id\", t0.\"jwt_secret\", t0.\"jwt_jwks\", t0.\"postgres_cdc_default\", t0.\"max_concurrent_users\", t0.\"max_events_per_second\", t0.\"max_bytes_per_second\", t0.\"max_channels_per_client\", t0.\"max_joins_per_second\", t0.\"suspend\", t0.\"inserted_at\", t0.\"updated_at\" FROM \"tenants\" AS t0 WHERE (t0.\"external_id\" = $1)"}
                    (realtime 2.28.23) lib/realtime/context_cache.ex:12: Realtime.ContextCache.apply_fun/3
                                                                                                                  (realtime 2.28.23) lib/realtime/tenants.ex:59: Realtime.Tenants.health_check/1
                                                                                 (realtime 2.28.23) lib/realtime_web/controllers/tenant_controller.ex:270: RealtimeWeb.TenantController.health/2
                                                                                 (realtime 2.28.23) lib/realtime_web/controllers/tenant_controller.ex:1: RealtimeWeb.TenantController.action/2
                                                                               (realtime 2.28.23) lib/realtime_web/controllers/tenant_controller.ex:1: RealtimeWeb.TenantController.phoenix_controller_pipeline/2
                                                                                                  (phoenix 1.7.7) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
                                                       (realtime 2.28.23) lib/realtime_web/endpoint.ex:1: RealtimeWeb.Endpoint.plug_builder_call/2
                                   (realtime 2.28.23) lib/realtime_web/endpoint.ex:1: RealtimeWeb.Endpoint.call/2      
                                                                                                                 service not healthy: [supabase_realtime_ProjectName]
Try rerunning the command with --debug to troubleshoot the error.
```

## System information

- OS: Windows
- Version of supabase-js: Version of supabase: latest releases of images, I believe 1.6.1 or 1.61?

**Comment by filipecabaco** [comment]
yes it looks like a failure in the migrations for some reason 🤔 can you provide more context?

**Comment by edgurgel** [comment]
Closing as we didn't get any feedback
